### ISSUE TITLE
Formatting change request

### ISSUE THREAD

**Issue by nerdler33** [axheron/ffxiv-dps-calc#114]
**Is your feature request related to a problem? Please describe.**
Minor OCD complaint that the decimal places are not consistent in the MP/min and DPS columns. Also would consider pluralizing number of adlos/eds/rezs etc per min. Really minor stuff, buut going to ask anyway :)

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by redshadowhero** [comment]
Example image:

![image](https://user-images.githubusercontent.com/971885/119694455-d6f4fa80-be12-11eb-90bc-fa8148e93825.png)

Maybe force format to 2 decimals in the client?

**Comment by nerdler33** [comment]
That was my opinion yes. Either that or force 1 or even 0. Decimal point
dps doesn't really matter.
